spring:
  application:
    name: NYX

  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/nyx_db
    username: root
    password: system

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true